version: "3"
services:
  db:
    container_name: postgresDB
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
  
volumes:
  postgres-db:
    external: false
    