name: Update Container on Portainer

on:
  push:
    branches:
      - development

jobs:
  update-container:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v2

     - name: Build and push Docker image
       env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       run: |
        echo "Iniciando la construcción y el empuje de la imagen Docker..."
        docker build -t socialworky/worky-backend:dev .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push socialworky/worky-backend:dev
        echo "Construcción y empuje de la imagen Docker completados."

     - name: Deploy stack to Portainer
       uses: carlrygart/portainer-stack-deploy@v1
       with:
         portainer-host: ${{ secrets.PORTAINER_HOST }}
         username: ${{ secrets.PORTAINER_USERNAME }}
         password: ${{ secrets.PORTAINER_PASSWORD }}
         stack-name: 'worky-backend-dev'
         stack-definition: 'docker-compose.yml'
         image: socialworky/worky-backend:dev
         template-variables: '{"SERVER_HOST": "${{ secrets.WORKY_SERVER_HOST_DEV }}", "APP_VERSION": "${{ secrets.WORKY_APP_VERSION_DEV }}", "APP_PORT": "${{ secrets.WORKY_APP_PORT_DEV }}", "DB_HOST": "${{ secrets.WORKY_DB_HOST_DEV }}", "DB_PORT": "${{ secrets.WORKY_DB_PORT_DEV }}", "DB_USERNAME": "${{ secrets.WORKY_DB_USERNAME_DEV }}", "DB_PASSWORD": "${{ secrets.WORKY_DB_PASSWORD_DEV }}", "DB_DATABASE": "${{ secrets.WORKY_DB_DATABASE_DEV }}", "DB_SSL": "${{ secrets.WORKY_DB_SSL_DEV }}", "JWT_SECRET": "${{ secrets.WORKY_JWT_SECRET_DEV }}", "MAIL_HOST": "${{ secrets.WORKY_MAIL_HOST_DEV }}", "MAIL_USER": "${{ secrets.WORKY_MAIL_USER_DEV }}", "MAIL_PASSWORD": "${{ secrets.WORKY_MAIL_PASSWORD_DEV }}", "MAIL_FROM": "${{ secrets.WORKY_MAIL_FROM_DEV }}", "POSTGRES_USER": "${{ secrets.WORKY_DB_USERNAME_DEV }}", "POSTGRES_PASSWORD": "${{ secrets.WORKY_DB_PASSWORD_DEV }}", "POSTGRES_DB": "${{ secrets.WORKY_DB_DATABASE_DEV }}", "PGADMIN_DEFAULT_PASSWORD": "losbar191184", "PGADMIN_DEFAULT_EMAIL": "soporte@worky.cl"}'
      
